language: java

services:
  - docker

install:
  - docker pull featx/playframework:sbt-1.2.8

script:  
  - docker build -t featx/permutation:1.0-SNAPSHOT .

#after_script: 
#  - docker login -u  
#  - docker push

#deploy:
#  provider:
